# syntax=docker/dockerfile:1
FROM golang:{{ .GoVersion }}-alpine AS builder
WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o app ./cmd/server

FROM gcr.io/distroless/base-debian12
WORKDIR /app
COPY --from=builder /src/app /app/{{ .ServiceName }}
COPY configs ./configs
ENV PORT=8080
EXPOSE 8080
ENTRYPOINT ["/app/{{ .ServiceName }}"]
